### ISSUE TITLE
Pixel-wise reconstruction loss

### ISSUE THREAD

**Issue by LiUzHiAn** [InterDigitalInc/FeatureStyleEncoder#1]
Hi, thanks for contributing this excellent work.

Could you please tell whether the L2 recon. loss is applied on `\hat{x}_2 = G(w, F)` for the real image case?  I feel a bit confused about this point when reading the paper. Thanks in advance.

**Comment by Xu-Yao** [comment]
> Hi, thanks for contributing this excellent work.
> 
> Could you please tell whether the L2 recon. loss is applied on `\hat{x}_2 = G(w, F)` for the real image case? I feel a bit confused about this point when reading the paper. Thanks in advance.

Hi, thank you for reading our paper. 

For the real image case, the pixel-wise reconstruction loss is not applied. For StyleGAN2, when generating the synthetic image with the projected latent code, we can feed the ground truth noise to the generator, thus the encoder need to only focus on the information which should be encoded in the latent code. Whereas for real images, we do not have the ground truth noises, thus the pixel-wise loss may force the encoder to encode the information related to noise into the latent code.

**Comment by LiUzHiAn** [comment]
Let me make some summarizations based on the paper and your informative reply:

- For the real image case, the pixel-wise reconstruction loss is applied for neither `\hat{x}_1 = G(w)` nor `\hat{x}_2 = G(w, F)`;
- For the synthetic image, the pixel-wise reconstruction loss is only applied on `\hat{x}_1 = G(w)`;
- The remaining terms including LPIPS, feature reconstruction, and face inversion losses are applied both on `\hat{x}_1` and `\hat{x}_2`, either for the real image or synthetic image.

If there is something wrong, please correct me. Thank you.

**Comment by Xu-Yao** [comment]
> Let me make some summarizations based on the paper and your informative reply:
> 
> * For the real image case, the pixel-wise reconstruction loss is applied for neither `\hat{x}_1 = G(w)` nor `\hat{x}_2 = G(w, F)`;
> * For the synthetic image, the pixel-wise reconstruction loss is only applied on `\hat{x}_1 = G(w)`;
> * The remaining terms including LPIPS, feature reconstruction, and face inversion losses are applied both on `\hat{x}_1` and `\hat{x}_2`, either for the real image or synthetic image.
> 
> If there is something wrong, please correct me. Thank you.

Yes that's right.

**Comment by LiUzHiAn** [comment]
Thank you. BTW, when will the source code be released?
