### ISSUE TITLE
What is the exact sturcture of feature prediction branch network?

### ISSUE THREAD

**Issue by LiUzHiAn** [InterDigitalInc/FeatureStyleEncoder#2]
Hi, sorry for bothering again. 

I wonder if it is convenient for you to share the structure of the network? Specifically, the feature prediction branch and latent prediction branch.  Thanks.

**Comment by Xu-Yao** [comment]
> Hi, sorry for bothering again.
> 
> I wonder if it is convenient for you to share the structure of the network? Specifically, the feature prediction branch and latent prediction branch. Thanks.

Hi, the structures of the two branches are described in section 3.2 _Encoding_ part. The latent branch contains N mapping networks, each expressed by a single fully connected layer. The feature branch is a convolutional network, which contains two convolution layers and batch normalization layers in between. I have started cleaning the code and will try to make it public as soon as possible.

**Comment by LiUzHiAn** [comment]
I've sent an email to you for some details, please check it. Thanks.

**Comment by LiUzHiAn** [comment]
Any activation layer between the two conv layers?

**Comment by Xu-Yao** [comment]
> I've sent an email to you for some details, please check it. Thanks.

Hi, I have updated my email address, could you send it again?

**Comment by LiUzHiAn** [comment]
I sent to your At Interdigital email before. Forward to your telecom-paris.fr email just now

**Comment by LiUzHiAn** [comment]
@Xu-Yao hi, did you receive the email now?
